lesson51/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using lesson51.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace lesson51.Controllers
{
    public class OrdersController : Controller
    {
        private readonly PhoneShopContext _context;

        public OrdersController(PhoneShopContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Orders.ToList());
        }
        public IActionResult Create()
        {
            ViewBag.Phones = new SelectList(_context.Phones, "Id", "Name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,User,Address,ContactPhone,PhoneId")] Order order)
        {
            if (ModelState.IsValid)
            {
              await  _context.AddAsync(order);
               await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Phones = new SelectList(_context.Phones, "Id", "Name");
            return View(order);
        }
    }
}

lesson51/Controllers/PhonesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using lesson51.Models;
using lesson51.ViewModels;

namespace lesson51.Controllers
{ 
      public enum SortInPhones
{
    NameAsc,

    NameDesc,
    CompanyAsc,

    CompanyDesc,

    PriceAsc, 
    PriceDesc,

    PointAsc,
    PointDesc
}

    public class PhonesController : Controller
    {

        private readonly PhoneShopContext _context;
        //private readonly IHostingEnvironment appEnvironment;
        public PhonesController(PhoneShopContext context)
        {
            _context = context;
            

        }

        // GET: Phones
        public async Task<IActionResult> Index(int? company, string name, int price,int points, SortInPhones sortPhones = SortInPhones.NameAsc, int page = 1)
        {
            IQueryable<Phone> phones = _context.Phones.Include(u => u.Company);

            if (company != null && company != 0)
            {
                phones = phones.Where(p => p.CompanId == company);
            }

            if (!String.IsNullOrEmpty(name))
            {
                phones = phones.Where(p => p.Name.Contains(name));

            }
            if (price != null && price != 0)
            {
                phones = phones.Where(p => p.Price == price);
            }
            if (points != null && points != 0)
            {
                phones = phones.Where(p => p.points == points);
            }

            ViewBag.NameSort = sortPhones == SortInPhones.NameAsc ? SortInPhones.NameDesc : SortInPhones.NameAsc;
            ViewBag.CompSort = sortPhones == SortInPhones.CompanyAsc ? SortInPhones.CompanyDesc : SortInPhones.CompanyAsc;
            ViewBag.PriceSort = sortPhones == SortInPhones.PriceAsc ? SortInPhones.PriceDesc : SortInPhones.PriceAsc;
            ViewBag.PointSort = sortPhones == SortInPhones.PointAsc ? SortInPhones.PointDesc : SortInPhones.PointAsc;
            switch (sortPhones)

            {

                case SortInPhones.NameDesc:

                    phones = phones.OrderByDescending(s => s.Name);

                    break;

                case SortInPhones.CompanyAsc:

                    phones = phones.OrderBy(s => s.Company.Name);

                    break;

                case SortInPhones.CompanyDesc:

                    phones = phones.OrderByDescending(s => s.Company.Name);

                    break;
                case SortInPhones.PriceAsc:

                    phones = phones.OrderBy(s => s.Price);

                    break;

                case SortInPhones.PriceDesc:

                    phones = phones.OrderByDescending(s => s.Price);

                    break;
                case SortInPhones.PointAsc:

                    phones = phones.OrderBy(s => s.Price);

                    break;

                case SortInPhones.PointDesc:

                    phones = phones.OrderByDescending(s => s.Price);

                    break;

                default:

                    phones = phones.OrderBy(s => s.Name);

                    break;

            }
            int pageSize = 5;
            var count = await phones.CountAsync();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            List<Company> companies = _context.Companies.ToList();
            companies.Insert(0, new Company { Name = "Все", id = 0});

            PhoneViewModel viewModel = new PhoneViewModel
            {
                phones = await phones.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync(),
                PageViewModel = pageViewModel,
                Phones = new SelectList(companies, "id", "Name", "Price"),
                Name = name,
                Price = price
            };



            return View(viewModel);
        }

        // GET: Phones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phones
                .Include(p => p.Company)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (phone == null)
            {
                return NotFound();
            }

            return View(phone);
        }

        // GET: Phones/Create

        public IActionResult Create()
        {
            ViewData["Companies"] = new SelectList(_context.Companies, "id", "Name");
            return View();
        }
        // POST: Phones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Company,Price, CompanId")] Phone phone)
        {
        
            if (ModelState.IsValid)
            {
                _context.Add(phone);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Companies"] = new System.Web.Mvc.SelectList(_context.Companies, "id", "Name");
            return View(phone);
        }
        public IActionResult MakeReview()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MakeReview([Bind("points, text,backer")]Phone phone) {

            if (ModelState.IsValid)
            {
               await _context.AddRangeAsync(phone.points, phone.text, phone.backer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
           
            return View(phone);

        }

        public IActionResult CreateCompany()
        {
            return View("Views/Companies/CreateCompany.cshtml");
        }
  
        // GET: Phones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phones.FindAsync(id);
            if (phone == null)
            {
                return NotFound();
            }
            return View(phone);
        }

        // POST: Phones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Company,Price, CompanId")] Phone phone)
        {
            if (id != phone.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(phone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhoneExists(phone.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(phone);
        }

      /*  public async Task<IActionResult> Download(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phones
                .FirstOrDefaultAsync(m => m.Id == id);
            if (phone == null)
            {
                return NotFound();
            }


            return View(phone);
        }*/

       /* public IActionResult ConfirmedDownload(int? id)
        {
            string filePath = Path.Combine(appEnvironment.ContentRootPath, "MyFiles/Phones.txt");
            string fileType = "application/text";
            string fileName = "Phones.txt";

            return PhysicalFile(filePath, fileType, fileName);
        }*/
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phone = await _context.Phones
                .FirstOrDefaultAsync(m => m.Id == id);
            if (phone == null)
            {
                return NotFound();
            }

            return View(phone);
        }



        // POST: Phones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var phone = await _context.Phones.FindAsync(id);
            _context.Phones.Remove(phone);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhoneExists(int id)
        {
            return _context.Phones.Any(e => e.Id == id);
        }
       /* public IActionResult Thanks()
        {
            ViewBag.Points = 10;
            return View();
        }*/
    }
}

lesson51/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using lesson51.Models;
using lesson51.ViewModels;

namespace lesson51.Controllers
{
    public enum SortState
    {
        NameAsc,

        NameDesc,

        AgeAsc,

        AgeDesc,

        CompanyAsc,

        CompanyDesc
    }
    public class UsersController : Controller
    {
        private readonly PhoneShopContext _context;

        public UsersController(PhoneShopContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index(int? company, string name, SortState sortUsers = SortState.NameAsc, int page = 1)
        {
            IQueryable<User> users= _context.Users.Include(u => u.Company);

            if (company != null && company != 0)
            {
                users = users.Where(p => p.CompanyId == company);
            }

            if (!String.IsNullOrEmpty(name))
            {
                users = users.Where(p => p.Name.Contains(name));

            }
         

            ViewBag.NameSort = sortUsers == SortState.NameAsc ? SortState.NameDesc : SortState.NameAsc;
            ViewBag.AgeSort = sortUsers == SortState.AgeAsc ? SortState.AgeDesc : SortState.AgeAsc;
            ViewBag.CompSort = sortUsers == SortState.CompanyAsc ? SortState.CompanyDesc : SortState.CompanyAsc;
            switch (sortUsers)

            {

                case SortState.NameDesc:

                    users = users.OrderByDescending(s => s.Name);

                    break;

                case SortState.CompanyAsc:

                    users = users.OrderBy(s => s.Company.Name);

                    break;

                case SortState.CompanyDesc:

                    users = users.OrderByDescending(s => s.Company.Name);

                    break;
                case SortState.AgeAsc:

                    users = users.OrderBy(s => s.Age);

                    break;

                case SortState.AgeDesc:

                    users = users.OrderByDescending(s => s.Age);

                    break;

                default:

                    users = users.OrderBy(s => s.Name);

                    break;

            }
            int pageSize = 5;
            var count = await users.CountAsync();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            List<Company> companies = _context.Companies.ToList();
            companies.Insert(0, new Company { Name = "Все", id = 0 });

            UserViewModel viewModel = new UserViewModel
            {
                users= await users.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync(),
                PageViewModel = pageViewModel,
                Companies = new SelectList(companies, "id", "Name"),
                Name = name

            };
            return View(viewModel);
               }
            // GET: Users/Details/5
            public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Company)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(_context.Companies, "id", "Name");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Age,CompanyId")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "id", "Name", user.CompanyId);
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "id", "Name", user.CompanyId);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Age,CompanyId")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "id", "Name", user.CompanyId);
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Company)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

lesson51/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin Page</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <a class="navbar-brand" asp-area="" asp-controller="Phones" asp-action="Index">Admin Page</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample03">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" asp-area="" asp-controller="Phones" asp-action="Index">Phones</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">More Actions</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown03">
                            <a class="dropdown-item" href="https://trollface.dk/">Free IPHONE 12</a>
                            <a class="dropdown-item" href="https://trollface.dk/">Free Moneys</a>
                            <a class="dropdown-item" href="https://trollface.dk/">Free Car</a>
                        </div>
                    </li>
                </ul>
                <form class="form-inline my-2 my-md-0">
                    <input class="form-control" type="text" placeholder="Search">
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AdminPage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

lesson51/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lesson51</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lesson51</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Phones" asp-action="Index">Phones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Companies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - lesson51 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

lesson51/Views/Shared/_PagePagination.cshtml
@model lesson51.ViewModels.PageViewModel

<nav aria-label="...">
    <ul class="pagination">
        @if (Model.HasPreviousPage)
        {
            int prevPage = @Model.PageNumber - 1;
            <li class="page-item disabled">
                <a class="page-link" asp-action="Index" asp-route-page="@prevPage" tabindex="-1" aria-disabled="false">Previous</a>
            </li>
            for (int i = 1; i < Model.PageNumber; i--)
            {
                <li class="page-item"><a class="page-link" asp-action="Index" asp-route-page="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">@Model.PageNumber<span class="sr-only">(current)</span></a>
        </li>

        @if (Model.HasNextPage)
        {

            for (int i = Model.PageNumber + 1; i <= Model.TotalPages; i++)
            {
                <li class="page-item"><a class="page-link" asp-action="Index" asp-route-page="@i">@i</a></li>

            }
            int nextPage = @Model.PageNumber + 1;
            <li class="page-item"><a class="page-link" asp-action="Index" asp-route-page="@nextPage">Next</a></li>
        }
    </ul>
</nav>